"""Regenerates the winmm proxy's complete export surface.

The proxy DLL is loaded under the name "winmm.dll", so EVERY module in the
process resolves its winmm imports against us - not just GForce.exe.  Exporting
only the subset the game itself needs is therefore a latent load failure for any
other DLL: Steam's steamwebrtc.dll imports timeSetEvent/timeKillEvent, and with
those missing the loader refused it outright ("entry point timeKillEvent not
found"), which took Steam Datagram Relay down with it.

Run from this directory with the real 32-bit winmm export dump available:

    dumpbin /exports %SystemRoot%\\SysWOW64\\winmm.dll > build\\winmm_exports.txt
    python gen_winmm_forwards.py

Functions with a hand-written implementation in winmm_proxy.cpp (fallbacks,
co-op bootstrap) stay hand-written; everything else becomes a naked jmp thunk.
Ordinals are copied from the real DLL so imports by ordinal keep working.
"""

import re
import sys

DUMP = "build/winmm_exports.txt"
DEF = "winmm_proxy.def"
INL = "winmm_forward.inl"

# Hand-written in winmm_proxy.cpp; keep their existing wrappers.
HAND_WRITTEN = [
    "mixerClose", "mixerGetControlDetailsA", "mixerGetDevCapsA", "mixerGetID",
    "mixerGetLineControlsA", "mixerGetLineInfoA", "mixerOpen",
    "mixerSetControlDetails", "timeBeginPeriod", "timeEndPeriod",
    "timeGetDevCaps", "timeGetTime", "waveInClose", "waveInMessage",
    "waveInOpen", "waveOutClose", "waveOutGetDevCapsW", "waveOutMessage",
    "waveOutOpen", "waveOutPause", "waveOutPrepareHeader", "waveOutReset",
    "waveOutRestart", "waveOutSetVolume", "waveOutUnprepareHeader",
    "waveOutWrite",
]


def parse_exports(path):
    exports = []
    pattern = re.compile(r"^\s+(\d+)\s+[0-9A-F]+\s+[0-9A-F]{8}\s+(\w+)\s*$")
    with open(path, encoding="utf-8", errors="replace") as dump:
        for line in dump:
            match = pattern.match(line)
            if match:
                exports.append((int(match.group(1)), match.group(2)))
    return exports


def parse_hand_written_def(path):
    """Keeps the hand-written entries' decorated-name entries verbatim.

    Only HAND_WRITTEN names are carried over - everything else is regenerated,
    so a change to the thunk naming scheme actually takes effect on a re-run.
    """
    entries = {}
    pattern = re.compile(r"^\s+(\w+)=(\S+)\s+@(\d+)")
    with open(path, encoding="utf-8") as definition:
        for line in definition:
            match = pattern.match(line)
            if match and match.group(1) in HAND_WRITTEN:
                entries[match.group(1)] = (match.group(2), int(match.group(3)))
    return entries


def main():
    exports = parse_exports(DUMP)
    if not exports:
        print("no exports parsed from " + DUMP, file=sys.stderr)
        return 1
    existing = parse_hand_written_def(DEF)

    forwarded = [(name, ordinal) for ordinal, name in exports
                 if name not in HAND_WRITTEN]

    with open(INL, "w", encoding="utf-8", newline="\r\n") as inl:
        inl.write("// GENERATED by gen_winmm_forwards.py - do not edit.\n")
        inl.write("// Every winmm export the proxy does not implement itself,"
                  " forwarded verbatim\n// to the real system DLL.\n")
        for index, (name, _) in enumerate(forwarded):
            inl.write("WINMM_FORWARD(%d, %s)\n" % (index, name))

    with open(DEF, "w", encoding="utf-8", newline="\r\n") as definition:
        definition.write("LIBRARY winmm\n")
        definition.write("EXPORTS\n")
        for ordinal, name in exports:
            if name in existing:
                symbol, saved_ordinal = existing[name]
                assert saved_ordinal == ordinal, name
            else:
                # No leading underscore: link.exe decorates an internal name
                # taken from a .def itself unless it already carries an @N
                # stdcall suffix, so "_proxy_fwd_X" gets looked up as
                # "__proxy_fwd_X" and fails with LNK2001.  The hand-written
                # entries keep their decorated "_proxy_X@N" form for that
                # same reason.
                symbol = "proxy_fwd_" + name
            definition.write("    %s=%s @%d\n" % (name, symbol, ordinal))

    print("exports=%d hand-written=%d forwarded=%d" %
          (len(exports), len(exports) - len(forwarded), len(forwarded)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
